import React, { useState } from 'react';
import { Card, Typography, Table, Tag, Button, Space, Popconfirm, Modal, Form, Input, Row, Col, message } from 'antd';
import { PlusOutlined, StopOutlined, CheckCircleOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;

export default function BillerManagement() {
  const [data, setData] = useState([
    { 
      key: '1', 
      code: 'EVN_HANOI', 
      name: 'Điện lực Hà Nội', 
      inquiryUrl: 'https://api.evnhanoi.vn/v1/inquiry',
      paymentUrl: 'https://api.evnhanoi.vn/v1/pay',
      pocket: 'pkt_evn_001',
      status: 'active'
    },
    { 
      key: '2', 
      code: 'VNPT_NET', 
      name: 'Viễn thông VNPT', 
      inquiryUrl: 'https://gateway.vnpt.vn/bill/check',
      paymentUrl: 'https://gateway.vnpt.vn/bill/settle',
      pocket: 'pkt_vnpt_002',
      status: 'active'
    },
  ]);

  const [isModalVisible, setIsModalVisible] = useState(false);
  const [form] = Form.useForm();

  const toggleStatus = (record) => {
    const updatedData = data.map(item => {
      if (item.key === record.key) {
        const newStatus = item.status === 'active' ? 'inactive' : 'active';
        message.success(`Biller ${item.code} đã được chuyển sang trạng thái ${newStatus.toUpperCase()}.`);
        return { ...item, status: newStatus };
      }
      return item;
    });
    setData(updatedData);
  };

  const handleAddSubmit = (values) => {
    const autoGeneratedPocket = 'pkt_' + values.code.toLowerCase() + '_' + Math.floor(Math.random() * 1000).toString().padStart(3, '0');
    const newBiller = {
      key: Date.now().toString(),
      ...values,
      pocket: autoGeneratedPocket,
      status: 'active'
    };
    setData([newBiller, ...data]);
    message.success(`Tạo mới Biller ${values.code} thành công.`);
    setIsModalVisible(false);
    form.resetFields();
  };

  const columns = [
    { title: 'Code', dataIndex: 'code', key: 'code', align: 'center', width: '15%', render: text => <Text strong>{text}</Text> },
    { title: 'Name', dataIndex: 'name', key: 'name', align: 'center', width: '20%' },
    { title: 'Inquiry URL', dataIndex: 'inquiryUrl', key: 'inquiryUrl', align: 'center', width: '20%', ellipsis: true, render: text => <a title={text}>{text}</a> },
    { title: 'Payment URL', dataIndex: 'paymentUrl', key: 'paymentUrl', align: 'center', width: '15%', ellipsis: true, render: text => <a title={text}>{text}</a> },
    { title: 'Receive Pocket ID', dataIndex: 'pocket', key: 'pocket', align: 'center', width: '15%', render: text => <Text code>{text}</Text> },
    { title: 'Status', dataIndex: 'status', key: 'status', align: 'center', width: '10%', render: text => <Tag color={text === 'active' ? 'processing' : 'error'} style={{ margin: 0 }}>{text.toUpperCase()}</Tag> },
    { title: 'Action', key: 'action', align: 'center', width: '5%', render: (_, record) => (
      <Popconfirm 
        title={record.status === 'active' ? "Vô hiệu hóa Biller này?" : "Kích hoạt Biller này?"} 
        onConfirm={() => toggleStatus(record)}
      >
        <Button 
          size="small" 
          danger={record.status === 'active'} 
          icon={record.status === 'active' ? <StopOutlined /> : <CheckCircleOutlined />} 
          type="text"
          style={record.status !== 'active' ? { color: '#10b981' } : {}}
        />
      </Popconfirm>
    )}
  ];

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
        <Button type="primary" shape="round" icon={<PlusOutlined />} onClick={() => setIsModalVisible(true)} style={{ background: '#0ea5e9' }}>Add Biller</Button>
      </div>
      <Card className="glass-card" bodyStyle={{ padding: 0, overflow: 'hidden' }}>
        <Table columns={columns} dataSource={data} pagination={false} rowClassName="smart-row" />
      </Card>

      <Modal
        title={<div style={{ fontSize: 18 }}><PlusOutlined style={{ color: '#0ea5e9', marginRight: 8 }}/> Thêm Biller mới</div>}
        open={isModalVisible}
        onCancel={() => setIsModalVisible(false)}
        footer={null}
        destroyOnClose
        width={600}
      >
        <Form form={form} layout="vertical" onFinish={handleAddSubmit} style={{ marginTop: 24 }}>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item label="Biller Code" name="code" rules={[{ required: true, message: 'Vui lòng nhập mã Biller' }]}>
                <Input placeholder="VD: WATER_HCM" size="large" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="Display Name" name="name" rules={[{ required: true, message: 'Vui lòng nhập tên hiển thị' }]}>
                <Input placeholder="VD: Cấp nước TP.HCM" size="large" />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item label="Inquiry URL (Step 3.1)" name="inquiryUrl" rules={[{ required: true, message: 'Vui lòng nhập URL tra cứu' }]}>
            <Input placeholder="https://api.domain.com/inquiry" size="large" />
          </Form.Item>
          <Form.Item label="Payment URL (Step 5.1)" name="paymentUrl" rules={[{ required: true, message: 'Vui lòng nhập URL thanh toán' }]}>
            <Input placeholder="https://api.domain.com/pay" size="large" />
          </Form.Item>

          <Form.Item style={{ marginBottom: 0, marginTop: 32, textAlign: 'right' }}>
            <Space>
              <Button onClick={() => setIsModalVisible(false)} size="large">Hủy bỏ</Button>
              <Button type="primary" htmlType="submit" size="large" style={{ background: '#0ea5e9' }}>
                Tạo Biller
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}
